export const routePath = {
    root: '/',
    dashboard: '/dashboard',
    licenses: '/licenses-and-nodes',
    profile: '/profile',
    search: '/search',
    faucet: '/faucet',
    buy: '/buy-r1',
    termsAndConditions: '/terms-and-conditions',
    privacyPolicy: '/privacy-policy',
    confirmEmail: '/confirm-email',
    notFound: '/404',
    unauthorized: '/unauthorized',
    kyc: '/kyc',
    admin: '/admin',
};
