name: Build and Release Ratio1 dApp

on:
    push:
        branches:
            - master

jobs:
    build-and-release:
        name: Build and Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Generate Semantic Version
              id: version
              uses: PaulHatch/semantic-version@v5.4.0
              with:
                  tag_prefix: 'v'
                  major_pattern: '(MAJOR)'
                  minor_pattern: '(feat|feature)'
                  version_format: '${major}.${minor}.${patch}'

            - name: Build React app with Vite
              run: npm run build
              env:
                  VITE_APP_VERSION: ${{ steps.version.outputs.version }}

            - name: Archive production build
              run: zip -r ratio1-dapp-build.zip dist

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.version.outputs.version_tag }}
                  name: v${{ steps.version.outputs.version }}
                  draft: false
                  prerelease: false
                  files: ratio1-dapp-build.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
